"""Add ScreenTime model

Revision ID: 039f7fa09661
Revises: 
Create Date: 2025-06-02 00:36:07.422161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '039f7fa09661'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screen_time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('daily_average', sa.Integer(), nullable=False),
    sa.Column('most_used_app', sa.String(length=100), nullable=False),
    sa.Column('weekly_change', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('screen_time')
    # ### end Alembic commands ###
